name: Build Vue App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Change to frontend directory
      run: cd frontend

    - name: Install dependencies
      run: npm install
      working-directory: ./frontend

    - name: Build
      run: npm run build-only
      working-directory: ./frontend

    - name: Copy files to target directory
      run: |
        mkdir -p ${{ github.workspace }}/app/src/main/assets/ui
        cp -r ./frontend/dist/* ${{ github.workspace }}/app/src/main/assets/ui/
    - name: Commit and Push
      run: |
        git config --global user.name 'Paul Goldschmidt'
        git config --global user.email 'github@goldschmidt.id'
        git add -f app/source/main/assets/ui/
        git commit -m "New UI Files"
        git push
