name: Build Vue App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Change to frontend directory
      run: cd frontend

    - name: Install dependencies
      run: npm install
      working-directory: ./frontend

    - name: Build
      run: npm run build
      working-directory: ./frontend

    - name: Copy files to target directory
      run: |
        mkdir -p /app/source/main/assets/ui
        cp -r ./frontend/dist/* /app/source/main/assets/ui/
